name: wanikaniapi CI

on:
  pull_request:
  push:
  schedule:
    # once a week: Sunday at 4 AM
    - cron: "0 4 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: "Go: Build"
        run: go build ./...

      - name: "Go: Test"
        run: go test ./...

      - name: "Check: Gofmt"
        run: scripts/check_gofmt.sh
